version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_manager
    volumes:
      - db_data:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d

volumes:
  db_data: